version: '3.8'

services:
  meicrosoft-customers-api:
    build:
      context: ../src
      dockerfile: Meicrosoft.Customer.API/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ConnectionStrings__CustomersConnection=Server=sqlserver;Database=MS_Customers;User Id=sa;Password=ms-customers#789;TrustServerCertificate=True
      - ASPNETCORE_ENVIRONMENT=Development
      - APPLY_MIGRATIONS=true
    networks:
      - app-network
    depends_on:
      - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=ms-customers#789
      - MSSQL_DATABASE=MS_Customers
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - app-network

volumes:
  sql_data:

networks:
  app-network:
    driver: bridge
